# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Move into Being
email: sarahmaeg@gmail.com
description: > # "Wholeness of Self Through Movement. We teach you how to find happiness in your body, and how to move effortlessly."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://twitter.com/SBootstrap
  - title: linkedin
    url: 
